title: Torchbearer Lab
description: Research and Project Space
remote_theme: pages-themes/minimal@v0.2.0
baseurl: "/torchbearerlab.github.io"
url: "https://meredithclikkie.github.io"

# This helps Jekyll find your posts
collections:
  posts:
    output: true

# Ensures your post shows up regardless of timezone
future: true

plugins:
  - jekyll-remote-theme
